spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deposit_reminder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
